# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Feb 24 16:01:14 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1051, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/roimanager.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1050, 640))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabImage = QtGui.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabImage.setFont(font)
        self.tabImage.setObjectName(_fromUtf8("tabImage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabImage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.listChan = QtGui.QListWidget(self.tabImage)
        self.listChan.setObjectName(_fromUtf8("listChan"))
        self.gridLayout_2.addWidget(self.listChan, 0, 0, 1, 2)
        self.label = QtGui.QLabel(self.tabImage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.labelMin = QtGui.QLabel(self.tabImage)
        self.labelMin.setObjectName(_fromUtf8("labelMin"))
        self.gridLayout_2.addWidget(self.labelMin, 2, 0, 1, 1)
        self.sliderMin = QtGui.QSlider(self.tabImage)
        self.sliderMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMin.setObjectName(_fromUtf8("sliderMin"))
        self.gridLayout_2.addWidget(self.sliderMin, 2, 1, 1, 1)
        self.labelMax = QtGui.QLabel(self.tabImage)
        self.labelMax.setObjectName(_fromUtf8("labelMax"))
        self.gridLayout_2.addWidget(self.labelMax, 3, 0, 1, 1)
        self.sliderMax = QtGui.QSlider(self.tabImage)
        self.sliderMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMax.setObjectName(_fromUtf8("sliderMax"))
        self.gridLayout_2.addWidget(self.sliderMax, 3, 1, 1, 1)
        self.groupBoxCm = QtGui.QGroupBox(self.tabImage)
        self.groupBoxCm.setObjectName(_fromUtf8("groupBoxCm"))
        self.gridLayout_2.addWidget(self.groupBoxCm, 5, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.tabImage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.sliderBlending = QtGui.QSlider(self.tabImage)
        self.sliderBlending.setMaximum(20)
        self.sliderBlending.setSingleStep(1)
        self.sliderBlending.setPageStep(2)
        self.sliderBlending.setProperty("value", 20)
        self.sliderBlending.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBlending.setObjectName(_fromUtf8("sliderBlending"))
        self.gridLayout_2.addWidget(self.sliderBlending, 4, 1, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 1)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        self.gridLayout_2.setRowMinimumHeight(2, 1)
        self.gridLayout_2.setRowMinimumHeight(3, 1)
        self.gridLayout_2.setRowMinimumHeight(4, 20)
        self.gridLayout_2.setRowMinimumHeight(5, 1)
        self.tabWidget.addTab(self.tabImage, _fromUtf8(""))
        self.tabRoi = QtGui.QWidget()
        self.tabRoi.setObjectName(_fromUtf8("tabRoi"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabRoi)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonRemoveRoi = QtGui.QPushButton(self.tabRoi)
        self.buttonRemoveRoi.setObjectName(_fromUtf8("buttonRemoveRoi"))
        self.gridLayout.addWidget(self.buttonRemoveRoi, 1, 1, 1, 1)
        self.listRoi = QtGui.QListView(self.tabRoi)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listRoi.sizePolicy().hasHeightForWidth())
        self.listRoi.setSizePolicy(sizePolicy)
        self.listRoi.setObjectName(_fromUtf8("listRoi"))
        self.gridLayout.addWidget(self.listRoi, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabRoi, _fromUtf8(""))
        self.tabMarkers = QtGui.QWidget()
        self.tabMarkers.setObjectName(_fromUtf8("tabMarkers"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabMarkers)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listWidget = QtGui.QListWidget(self.tabMarkers)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_4.addWidget(self.listWidget, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tabMarkers)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMarkers, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineeditAtlasRef = QtGui.QLineEdit(self.centralwidget)
        self.lineeditAtlasRef.setMaxLength(10)
        self.lineeditAtlasRef.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineeditAtlasRef.setObjectName(_fromUtf8("lineeditAtlasRef"))
        self.horizontalLayout_3.addWidget(self.lineeditAtlasRef)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.groupBoxData = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxData.setObjectName(_fromUtf8("groupBoxData"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBoxData)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonSaveData = QtGui.QPushButton(self.groupBoxData)
        self.buttonSaveData.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonSaveData.setObjectName(_fromUtf8("buttonSaveData"))
        self.horizontalLayout_2.addWidget(self.buttonSaveData)
        self.buttonLoadData = QtGui.QPushButton(self.groupBoxData)
        self.buttonLoadData.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonLoadData.setObjectName(_fromUtf8("buttonLoadData"))
        self.horizontalLayout_2.addWidget(self.buttonLoadData)
        self.verticalLayout_2.addWidget(self.groupBoxData)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 1, 1, 1)
        self.buttonHome = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHome.sizePolicy().hasHeightForWidth())
        self.buttonHome.setSizePolicy(sizePolicy)
        self.buttonHome.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonHome.setMaximumSize(QtCore.QSize(32, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/home.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHome.setIcon(icon1)
        self.buttonHome.setIconSize(QtCore.QSize(20, 20))
        self.buttonHome.setObjectName(_fromUtf8("buttonHome"))
        self.gridLayout_6.addWidget(self.buttonHome, 1, 2, 1, 1)
        self.buttonZoom = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonZoom.sizePolicy().hasHeightForWidth())
        self.buttonZoom.setSizePolicy(sizePolicy)
        self.buttonZoom.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonZoom.setMaximumSize(QtCore.QSize(32, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/zoom.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoom.setIcon(icon2)
        self.buttonZoom.setIconSize(QtCore.QSize(20, 20))
        self.buttonZoom.setCheckable(True)
        self.buttonZoom.setObjectName(_fromUtf8("buttonZoom"))
        self.gridLayout_6.addWidget(self.buttonZoom, 1, 3, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 1, 4, 1, 1)
        self.buttonAddMarker = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddMarker.sizePolicy().hasHeightForWidth())
        self.buttonAddMarker.setSizePolicy(sizePolicy)
        self.buttonAddMarker.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonAddMarker.setMaximumSize(QtCore.QSize(32, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/addmarker.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAddMarker.setIcon(icon3)
        self.buttonAddMarker.setIconSize(QtCore.QSize(20, 20))
        self.buttonAddMarker.setCheckable(True)
        self.buttonAddMarker.setObjectName(_fromUtf8("buttonAddMarker"))
        self.gridLayout_6.addWidget(self.buttonAddMarker, 1, 5, 1, 1)
        self.buttonRemoveMarker = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRemoveMarker.sizePolicy().hasHeightForWidth())
        self.buttonRemoveMarker.setSizePolicy(sizePolicy)
        self.buttonRemoveMarker.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonRemoveMarker.setMaximumSize(QtCore.QSize(32, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/removemarker.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRemoveMarker.setIcon(icon4)
        self.buttonRemoveMarker.setIconSize(QtCore.QSize(20, 20))
        self.buttonRemoveMarker.setCheckable(True)
        self.buttonRemoveMarker.setObjectName(_fromUtf8("buttonRemoveMarker"))
        self.gridLayout_6.addWidget(self.buttonRemoveMarker, 1, 6, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_6.addWidget(self.line_4, 1, 7, 1, 1)
        self.buttonAddRoi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddRoi.sizePolicy().hasHeightForWidth())
        self.buttonAddRoi.setSizePolicy(sizePolicy)
        self.buttonAddRoi.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonAddRoi.setMaximumSize(QtCore.QSize(32, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/roi.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAddRoi.setIcon(icon5)
        self.buttonAddRoi.setIconSize(QtCore.QSize(20, 20))
        self.buttonAddRoi.setCheckable(True)
        self.buttonAddRoi.setObjectName(_fromUtf8("buttonAddRoi"))
        self.gridLayout_6.addWidget(self.buttonAddRoi, 1, 8, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_6.addWidget(self.line_5, 1, 9, 1, 1)
        self.buttonShowMarkers = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonShowMarkers.sizePolicy().hasHeightForWidth())
        self.buttonShowMarkers.setSizePolicy(sizePolicy)
        self.buttonShowMarkers.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonShowMarkers.setMaximumSize(QtCore.QSize(32, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/markervisible.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/markerhidden.svg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonShowMarkers.setIcon(icon6)
        self.buttonShowMarkers.setIconSize(QtCore.QSize(20, 20))
        self.buttonShowMarkers.setCheckable(True)
        self.buttonShowMarkers.setChecked(False)
        self.buttonShowMarkers.setObjectName(_fromUtf8("buttonShowMarkers"))
        self.gridLayout_6.addWidget(self.buttonShowMarkers, 1, 10, 1, 1)
        self.buttonShowRoi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonShowRoi.sizePolicy().hasHeightForWidth())
        self.buttonShowRoi.setSizePolicy(sizePolicy)
        self.buttonShowRoi.setMinimumSize(QtCore.QSize(0, 32))
        self.buttonShowRoi.setMaximumSize(QtCore.QSize(32, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/roivisible.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/roihidden.svg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonShowRoi.setIcon(icon7)
        self.buttonShowRoi.setIconSize(QtCore.QSize(20, 20))
        self.buttonShowRoi.setCheckable(True)
        self.buttonShowRoi.setChecked(False)
        self.buttonShowRoi.setObjectName(_fromUtf8("buttonShowRoi"))
        self.gridLayout_6.addWidget(self.buttonShowRoi, 1, 11, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 12, 1, 1)
        self.canvas = MplCanvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.canvas.setObjectName(_fromUtf8("canvas"))
        self.gridLayout_6.addWidget(self.canvas, 0, 0, 1, 13)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 5)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1051, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpenNext = QtGui.QAction(MainWindow)
        self.actionOpenNext.setObjectName(_fromUtf8("actionOpenNext"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenNext)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ROI Manager", None))
        self.label.setText(_translate("MainWindow", "Display range", None))
        self.labelMin.setText(_translate("MainWindow", "Min", None))
        self.sliderMin.setToolTip(_translate("MainWindow", "Minimum display value", None))
        self.labelMax.setText(_translate("MainWindow", "Max", None))
        self.sliderMax.setToolTip(_translate("MainWindow", "Maximum display value", None))
        self.groupBoxCm.setTitle(_translate("MainWindow", "Colourmap", None))
        self.label_3.setText(_translate("MainWindow", "Blending", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("MainWindow", "Image", None))
        self.buttonRemoveRoi.setText(_translate("MainWindow", "Remove", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRoi), _translate("MainWindow", "ROIs", None))
        self.pushButton.setText(_translate("MainWindow", "New marker set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMarkers), _translate("MainWindow", "Markers", None))
        self.label_2.setText(_translate("MainWindow", "Atlas reference:", None))
        self.lineeditAtlasRef.setToolTip(_translate("MainWindow", "Atlas reference number", None))
        self.groupBoxData.setTitle(_translate("MainWindow", "Data", None))
        self.buttonSaveData.setToolTip(_translate("MainWindow", "Save data set", None))
        self.buttonSaveData.setText(_translate("MainWindow", "Save", None))
        self.buttonLoadData.setToolTip(_translate("MainWindow", "Load data set", None))
        self.buttonLoadData.setText(_translate("MainWindow", "Load", None))
        self.buttonHome.setToolTip(_translate("MainWindow", "Reset view", None))
        self.buttonZoom.setToolTip(_translate("MainWindow", "Toggle pan/zoom", None))
        self.buttonAddMarker.setToolTip(_translate("MainWindow", "Add marker", None))
        self.buttonRemoveMarker.setToolTip(_translate("MainWindow", "Remove marker", None))
        self.buttonAddRoi.setToolTip(_translate("MainWindow", "Add ROI", None))
        self.buttonShowMarkers.setToolTip(_translate("MainWindow", "View/hide markers", None))
        self.buttonShowRoi.setToolTip(_translate("MainWindow", "View/hide ROIs", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open PatchMaster file", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionOpenNext.setText(_translate("MainWindow", "Open next", None))
        self.actionOpenNext.setShortcut(_translate("MainWindow", "Ctrl+N", None))

from mplcanvas import MplCanvas
import resources_rc
